from typing import Tuple
from .typedefs import StateID
from .symbol import Symbol

def parse_arc_definition(line: str) -> Tuple[int, ...]: ...

class Arc:
    def __init__(self, state: StateID, upper: Symbol, lower: Symbol, destination: StateID) -> None: ...
    @property
    def state(self) -> StateID: ...
    @property
    def upper(self) -> Symbol: ...
    @property
    def lower(self) -> Symbol: ...
    @property
    def destination(self) -> StateID: ...
