download: crk-descriptive-analyzer.fomabin

crk-descriptive-analyzer:
	curl --fail --silent -LO https://github.com/UAlbertaALTLab/plains-cree-fsts/releases/download/20190308054913-245004d/crk-descriptive-analyzer.fomabin
