name: Upload Python Package

on:
  push:
    tags:
     - 'v*'

jobs:
  # This one uses poetry.
  publish-sdist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Coerce poetry into creating a setup.py
      run: |
        make setup.py
    - name: Upload setup.py for use in other actions
      uses: actions/upload-artifact@v2
      with:
        name: setup.py
        path: setup.py
    - name: Publish sdist
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry build --format=sdist
        poetry publish --username=__token__ --password="$PYPI_PASSWORD"

  publish-bdist-manylinux:
    needs: publish-sdist

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
         python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
        rm -f pyproject.toml
    - uses: actions/download-artifact@v2
      with:
        name: setup.py
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2010_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38'
    - name: Publish wheels tp PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload wheelhouse/*-manylinux*.whl
